name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Prepare cached Node.js install
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the library
        run: npm run build

      - name: Run tests
        run: npm run test
